import streamlit as st
from PIL import Image

def tab2_func():
    st.markdown('#### 풍차돌리기란?')
    st.markdown('카카오 26주 적금을 총 :orange[**26개**]를 운용하는 것. 매주 같은 요일에 1개씩 개설 !!')
    st.markdown('27주차 이후부터 효과를 본다.')
    st.divider()
    st.markdown('##### 장점')
    st.markdown('- 26주를 완성했을 때 :blue[고금리 효과(연 7%)]를 볼 수 있다.')
    st.markdown('- 매주 하나씩 :blue[쌓아가는] 재미가 있다.')
    st.markdown('- 26개 완성 후 :blue[매주 이자]를 받는 재미가 있다.')
    st.markdown('- 26주 이후로는 :blue[추가로 들어가는] 돈이 없다.')
    st.divider()
    st.markdown('##### 단점')
    st.markdown('- :red[시간]과 :red[끈기]가 필요하다.\n')
    st.markdown('- 매주 챙겨야 하는 :red[번거로움]이 있다. (납입 실패 시 :red[우대금리 X])')
    st.markdown('- 한 번이라도 :red[자동이체 실패]하면, 통장 이율이 :red[3.5%]가 된다.')
    st.markdown('- 생각보다 :red[부담]된다. 뒤로 갈수록 :red[매주 큰 돈]이 빠져 나간다.')
    
    st.divider()
    image = Image.open("./assets/kakao_saving.jpg")
    st.image(image, caption='kakao saving')

def tab3_func():
    st.markdown('1. :orange[카카오뱅크] 어플 실행 → 로그인 (카카오뱅크 계좌 필요)')
    image = Image.open("./assets/step1.jpg")
    st.image(image)
    st.divider()
    st.markdown('2. 계좌 목록 하단에 있는 :orange[+] 버튼 클릭')
    image = Image.open("./assets/step2.png")
    st.image(image)
    st.divider()
    st.markdown('3. :orange[26주 적금] 선택 → 26주 적금 신청하기')
    image = Image.open("./assets/step3.png")
    st.image(image)
    st.divider()
    st.markdown('4. 계좌 개설 약관 동의')
    st.divider()
    st.markdown('5. :orange[증액 금액] 선택 (계산기로 먼저 :orange[총 필요 금액] 확인 후 선택) ')
    image = Image.open("./assets/step5.png")
    st.image(image)
    st.divider()
    st.markdown('6. 만기설정 → 만기 시 :orange[자동해지]')
    image = Image.open("./assets/step6.png")
    st.image(image)
    st.divider()
    st.markdown('7. :orange[매주 같은 요일]에 동일한 방법으로 반복')
    st.markdown('*7월 21일 금요일 1호 개설  → 7월 28일 금요일 2호 개설 → 8월 4일 금요일 3호 개설 → ...*')
